version: '3.8'

services:
  watchlistr-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: watchlistr-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
