version: '3.8'

services:
  ttvdb-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ttvdb-proxy
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
